---

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install mopidy external extensions.
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ mopidy_external_extensions }}"
  notify: restart mopidy

- name: Configure Mopidy
  ini_file:
    dest: /etc/mopidy/mopidy.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ mopidy_settings }}"
  notify: restart mopidy

- name: Ensure Mopidy is started on boot.
  service:
    name: mopidy
    state: started
    enabled: yes
