---

- name: Trust Mopidy developer GPG key.
  apt_key:
    url: https://apt.mopidy.com/mopidy.gpg
    state: present

- name: Ensure Mopidy repository is available.
  apt_repository:
    repo: deb http://apt.mopidy.com/ stable main contrib non-free
    state: present

- name: Ensure mopidy is installed.
  apt:
    name: mopidy
    state: present

- name: Install mopidy extensions.
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ mopidy_extensions }}"
  notify: restart mopidy

- name: Ensure pip is available.
  apt:
    name: python-pip
    state: present
  when: mopidy_external_extensions
